spring.profiles.active=prod-yb
spring.security.authentication.jwt.validity=6000000
spring.security.authentication.jwt.secret=ab9ae52e116f4ca0d2415c75d23775fad043c1bb5774298ee1e0f34390ff09a76fe2169d16727e510046288ca913ce80
spring.main.allow-bean-definition-overriding=true
server.max-http-request-header-size=100KB
#spring.main.lazy-initialization=false
logging.level.org.springframework.boot.autoconfigure=DEBUG
